FROM ubuntu:16.04 

RUN apt-get update -y && apt-get install wget -y
RUN apt-get install openjdk-9-jre -y
RUN wget https://raw.githubusercontent.com/minepicco/dockerfiles/master/pingfederate/8.3.3/pf-install.sh
RUN chmod +x pf-install.sh
RUN "./pf-install.sh -v 9.1.3"
ENTRYPOINT ["sh", "-c", "/home/pingfederate/bin/run.sh", "BACKGROUND"]

EXPOSE 9999 9031 1099
