from centos:6

RUN yum -y update && yum -y install wget
RUN wget https://raw.githubusercontent.com/minepicco/dockerfiles/master/pingfederate/9.1.3/pf-install.sh
RUN chmod +x pf-install.sh
CMD ["./pf-install.sh -v 9.1.3"]
ENTRYPOINT ["sh", "-c", "/home/pingfederate/bin/run.sh", "BACKGROUND"]

EXPOSE 9999 9031 1099
