from centos:6

RUN yum -y update && yum install -y java-1.8.0-openjdk-devel
RUN yum -y install wget
RUN wget https://raw.githubusercontent.com/minepicco/dockerfiles/master/pingfederate/8.3.3/pf-install.sh
RUN chmod +x pf-install.sh; ./pf-install.sh -v 8.3.3

EXPOSE 9999 9031 1099
