FROM centos:7 

RUN yum update -y && yum install wget -y
RUN yum -y install java-1.8.0-openjdk java-1.8.0-openjdk-devel 
RNN echo "export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b12-0.el7_5.x86_64" >> /etc/profile

#RUN echo "export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.181-3.b13.el7_5.x86_64" >> /etc/profile
RUN echo "export PATH=$PATH:$JAVA_HOME/bin" >> /etc/profile
RUN echo "export CLASSPATH=.:$JAVA_HOME/jre/lib:$JAVA_HOME/lib:$JAVA_HOME/lib/tools.jar" >> /etc/profile
RUN echo "export PF_USER=root" >> /etc/profile
RUN wget https://raw.githubusercontent.com/minepicco/dockerfiles/master/pingfederate/9.1.2/pf-install-9.1.2.sh
RUN chmod +x pf-install-9.1.2.sh
RUN ./pf-install-9.1.2.sh
RUN echo $JAVA_HOME
# RUN cd $JAVA_HOME
RUN chown root. -R /usr/local/pingfederate1-9.1.2/
RUN chmod 755 -R /usr/local/pingfederate1-9.1.2/
RUN chown root. -R /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b12-0.el7_5.x86_64
RUN chmod 755 -R /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b12-0.el7_5.x86_64
ENTRYPOINT ["sh", "-c", "/usr/local/pingfederate1-9.1.2/pingfederate/sbin/pingfederate-run.sh", "BACKGROUND"]

EXPOSE 9999 9031 1099
