FROM centos:7 

RUN yum update -y && yum install wget -y
RUN yum -y install java-1.8.0-openjdk java-1.8.0-openjdk-devel
RUN wget https://raw.githubusercontent.com/minepicco/dockerfiles/master/pingfederate/9.1.2/pf-install-9.1.2.sh
RUN chmod +x pf-install-9.1.2.sh
RUN ./pf-install-9.1.2.sh
ENTRYPOINT ["sh", "-c", "/usr/local/pingfederate1-9.1.2/pingfederate/sbin/pingfederate-run.sh", "BACKGROUND"]

EXPOSE 9999 9031 1099
